### ISSUE TITLE
Make task-master and task-filer images configurable

### ISSUE THREAD

**Issue by Myskmadra** [EMBL-EBI-TSI/tesk-api#8]
Hey,

I would like to use a Cromwell server as a front for TESK and it seems that the way Cromwell submits tasks to TESK is not in accordance to what TESK requires in terms of file down- and upload. Hence, I changed some minor things in the task-filer and task-manager to adjust it to my needs/Cromwell's output. However, I need to change the images used by the tesk-api in order to validate that it works. I was wondering if you could set up env variables for the images used in order to allow me to use custom images.

**Comment by aniewielska** [comment]
Hello,
1) TBH we never tried Cromwell with TESK and shared filesystem. Options that work:
- cwl-tes +  shared file system + TESK
- Cromwell + FTP + TESK.
It is likely that it will work, but might require some changes at any ends.
2) Changing the image for taskmaster is already available, but not well documented - tesk.api.taskmaster.image-name <-- that is a property responsible for taskmaster image and in Spring Boot way of externalising configuration you can override the value in multiple ways. One way is to set an environment variable TESK_API_TASKMASTER_IMAGE_NAME for TESK API.
3) Changing the image for filer is already partially available, but at API side depends on this PR: https://github.com/EMBL-EBI-TSI/tesk-api/pull/6 I hope to accept it soon.

I will keep this issue open and close it, once changing images has been made available.

**Comment by Myskmadra** [comment]
Thank you for getting back to me so fast. I set TESK_API_TASKMASTER_IMAGE_NAME to the image I want to test and it works fine. I also changed the default image of the filer in the taskmaster and it uses the test image. I will see if I get it to work and get back to you. 😃

**Comment by aniewielska** [comment]
The PR #6 has been accepted and now it should be possible to change both images - taskmaster and filer, starting with [this](https://github.com/EMBL-EBI-TSI/tesk-api/releases/tag/v0.7.2) release.
I added some more information to [docs](https://github.com/EMBL-EBI-TSI/tesk-api#externalized-configuration)
